# Generated by Django 5.0.7 on 2024-07-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='item',
            field=models.ManyToManyField(to='app.item'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='mobileno',
            field=models.CharField(max_length=10),
        ),
    ]
